NDefines.NAir.AIR_WING_MAX_STATS_ATTACK = 800
NDefines.NAir.AIR_WING_MAX_STATS_DEFENCE = 800
NDefines.NAir.AIR_WING_MAX_STATS_AGILITY = 800
NDefines.NAir.AIR_WING_MAX_STATS_BOMBING = 800
NDefines.NAir.AIR_WING_MAX_STATS_SPEED = 3000

NDefines.NAir.BIGGEST_AGILITY_FACTOR_DIFF = 8.0
NDefines.NAir.BIGGEST_SPEED_FACTOR_DIFF = 5.0

NDefines.NAir.MISSION_COMMAND_POWER_COSTS = {
			0.0, -- AIR_SUPERIORITY
			0.0, -- CAS
			0.0, -- INTERCEPTION
			0.0, -- STRATEGIC_BOMBER
			0.0, -- NAVAL_BOMBER
			0.0, -- DROP_NUKE
			0.0, -- PARADROP
			0.0, -- NAVAL_KAMIKAZE
	        	0.0, -- PORT_STRIKE
			0.0, -- ATTACK_LOGISTICS
			0.02, -- AIR_SUPPLY
			0.0, -- TRAINING
			0.0, -- NAVAL_MINES_PLANTING
			0.0, -- NAVAL_MINES_SWEEPING
			0.0, -- RECON
			0.0, -- NAVAL_PATROL
		}

NDefines.NAir.USE_SINGLE_NAVAL_ARMAMENT_CATEGORY = false


NDefines.NDoctrines.TRAINING_MASTERY_GAIN_FACTOR = 0.2