-- Carrier Battle

NDefines.NAir.DISRUPTION_FACTOR_CARRIER = 10.0			-- Vanilla: 6
NDefines.NNavy.CAPITAL_ONLY_COMBAT_ACTIVATE_TIME = 9	-- Vanilla: 6
NDefines.NNavy.ALL_SHIPS_ACTIVATE_TIME = 11				-- Vanilla: 8

NDefines.NNavy.SHIP_SILHOUETTE_VALUE_PLANES_CARRIER = 30	-- Vanilla: 16
NDefines.NNavy.NAVAL_COMBAT_AIR_CARRIER_TARGET_BASE = 50	-- Vanilla: 10
NDefines.NNavy.NAVAL_COMBAT_AIR_CARRIER_TARGET_SCALE = 250	-- Vanilla: 200

NDefines.NAir.CARRIER_SIZE_STAT_INCREMENT = 5					-- Vanilla: 10
NDefines.NNavy.DOMINANCE_PER_SHIP_PER_CARRIER_SIZE = 0.04		-- Vanilla: 0.1
NDefines.NNavy.DOMINANCE_PER_SHIP_PER_HEAVY_GUN_ATTACK = 0.015 	-- Vanilla: 0.01


-- Screening

NDefines.NNavy.SCREEN_RATIO_FOR_FULL_SCREENING_FOR_CAPITALS = 2		-- Vanilla: 3
NDefines.NNavy.SCREEN_RATIO_FOR_FULL_SCREENING_FOR_CONVOYS = 0.25	-- Vanilla: 0.5
NDefines.NNavy.CAPITAL_RATIO_FOR_FULL_SCREENING_FOR_CONVOYS = 0.1	-- Vanilla: 0.25

-- Bigger Fleet Penalties

NDefines.NNavy.MAX_POSITIONING_PENALTY_FROM_HIGHER_SHIP_RATIO = 2	-- Vanilla: 0.75
NDefines.NNavy.HIGHER_SHIP_RATIO_POSITIONING_PENALTY_FACTOR = 1		-- Vanilla: 0.25
NDefines.NNavy.MIN_SHIPS_FOR_HIGHER_SHIP_RATIO_PENALTY = 12			-- Vanilla: 4

NDefines.NNavy.DAMAGE_PENALTY_ON_MINIMUM_POSITIONING = 0.75			-- Vanilla: 0.5
NDefines.NNavy.SCREENING_EFFICIENCY_PENALTY_ON_MINIMUM_POSITIONING = 1	-- Vanilla: 0.5
NDefines.NNavy.AA_EFFICIENCY_PENALTY_ON_MINIMUM_POSITIONING = 0.9	-- Vanilla: 0.7

-- Dominance & Supply

NDefines.NNavy.DOMINANCE_CONTROLLED_THRESHOLD_RATIO = 0.7		-- Vanilla: 0.6

NDefines.NNavy.SUPPLY_CONVOY_FACTOR = 0.5			-- Vanilla: 0.25